// File generated by FlutterFire CLI / manually configured for NTFMS project.
// NTFMS Firebase project: ntfms2026

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default FirebaseOptions for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  // Web / iOS / Android all share the same Firebase project —
  // only the platform-specific appId differs.

  static const FirebaseOptions web = FirebaseOptions(
    apiKey:            'AIzaSyDQxa2ysMhzpPNTsbA2TKxXEFIiAETXxQQ',
    authDomain:        'ntfms2026.firebaseapp.com',
    projectId:         'ntfms2026',
    storageBucket:     'ntfms2026.firebasestorage.app',
    messagingSenderId: '395993702197',
    appId:             '1:395993702197:web:01f1388c5697660784f67c',
  );

  // NOTE: Download google-services.json from Firebase Console →
  // Project Settings → Your apps → Android app and place it at:
  //   android/app/google-services.json
  // Then change the appId below to match your Android app's appId.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey:            'AIzaSyDQxa2ysMhzpPNTsbA2TKxXEFIiAETXxQQ',
    authDomain:        'ntfms2026.firebaseapp.com',
    projectId:         'ntfms2026',
    storageBucket:     'ntfms2026.firebasestorage.app',
    messagingSenderId: '395993702197',
    appId:             '1:395993702197:web:01f1388c5697660784f67c', // Replace with Android appId
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'AIzaSyDQxa2ysMhzpPNTsbA2TKxXEFIiAETXxQQ',
    authDomain:        'ntfms2026.firebaseapp.com',
    projectId:         'ntfms2026',
    storageBucket:     'ntfms2026.firebasestorage.app',
    messagingSenderId: '395993702197',
    appId:             '1:395993702197:web:01f1388c5697660784f67c', // Replace with iOS appId
  );
}
